src/QAT/qat/purr/backends/verification.py
src/tests/test_verification.py

Very little here, but a template for other people to extend later.

Add skeleton for verification engine

---

.gitattributes

Refine linguist paths

---

.gitattributes
.github/CODEOWNERS
.github/ISSUE_TEMPLATE/bug_report.md
.github/ISSUE_TEMPLATE/feature_request.md
.github/workflows/cla-assistant.yaml
README.rst
contributor_license_agreement.md
poetry.lock
src/QAT/qat/purr/backends/verification.py
src/tests/files/qir/base_profile_ops.ll
src/tests/files/qir/basic_cudaq.ll
src/tests/test_qir.py
src/tests/test_verification.py

Just updating with the latest changes from main.

Update from main

---

src/QAT/qat/purr/integrations/qasm.py
src/tests/files/qasm/qasm3/lark_parsing_test.qasm

An updated version of #17 - when I rebased my fork to get rid of the commits with my local contributor, Github deleted the PR, so I'm making this new one. This PR also uncomments the `get_phase` and `get_frequency` test cases as requested by @chemix-lunacy.

fix get phase and frequency with tests

---

.github/workflows/cla-assistant.yaml
examples/builder.py
examples/plot_pulse_buffers.py
examples/real_time_chip_sim.py
poetry.lock
src/QAT/qat/purr/compiler/devices.py

Just starting some examples, I'll continue to push more as I think of them, please push straight to branch with more.
Will add more comments into the files shortly, too. Just wanted to kick off the PR

Some initial examples

---

src/QAT/qat/purr/compiler/builders.py
src/QAT/qat/purr/compiler/execution.py
src/QAT/qat/purr/compiler/instructions.py
src/tests/test_instructions.py
src/tests/test_qat.py

Efficiency improvements:
- Efficient entanglement checker.
- Keep track of pulse channel duration as we go.
- Take the final instruction as our 'end' sample.
- Common add_channel method.
- Use sets for unique sets.
- Fix duplicate quantum targests.

Efficiency improvements

---

src/QAT/qat/purr/compiler/config.py

To be within object or not, will see.

Add additional documentation to compiler config

---

src/QAT/qat/purr/integrations/qasm.py
src/tests/files/qasm/qasm3/lark_parsing_test.qasm

Porting bugfix made by ayush-pancholy from main branch. [#18](https://github.com/oqc-community/qat/pull/18)

Fix get phase and frequency.

---

src/QAT/qat/purr/compiler/execution.py
src/QAT/qat/purr/integrations/qasm.py
src/tests/files/qasm/qasm3/waveform_tests/internal_waveform_tests.qasm
src/tests/test_qasm.py

Porting tidy up from main, [OpenPulse Tidy](https://github.com/oqc-community/qat/pull/14/commits/e37e66b62529365b060f74223a5568e406d04613)

OpenPulse Tidy.

---

src/QAT/qat/purr/compiler/config.py
src/QAT/qat/purr/compiler/execution.py
src/QAT/qat/purr/compiler/frontends.py
src/QAT/qat/purr/error_mitigation/readout_mitigation.py
src/tests/test_readout_mitigation.py

This clears out a few review comments raised in Jamie's readout mitigation PR: https://github.com/oqc-community/qat/pull/4. Hopefully this speeds up the merge/integration cc/ @jdavid-oqc

Review changes for Jamie's work on readout mitigation

---

src/QAT/qat/purr/backends/live_devices.py

Fixing recursion bugs when closing instruments.

Changes to live

---

src/QAT/qat/__init__.py
src/QAT/qat/purr/compiler/execution.py
src/QAT/qat/purr/compiler/experimental/frontends.py
src/QAT/qat/purr/compiler/interrupt.py
src/QAT/qat/purr/compiler/runtime.py
src/tests/files/qasm/qasm2/ghz_2.qasm
src/tests/test_experimental_frontends.py
src/tests/test_qasm.py
src/tests/test_quantum_backend.py

- Ported execution interrupt
- Includes latest fixes

Ported execution interrupt

---

src/QAT/qat/purr/backends/qiskit_simulator.py
src/QAT/qat/purr/compiler/config.py
src/QAT/qat/purr/compiler/error_mitigation/readout_mitigation.py
src/QAT/qat/purr/compiler/hardware_models.py
src/QAT/qat/purr/compiler/runtime.py
src/tests/test_qasm.py
src/tests/test_quantum_backend.py
src/tests/test_readout_mitigation.py

The PR here https://github.com/oqc-community/qat/pull/70 fails for some reason. Trying this new one that's not coming from a private fork

Ported error mitigation

---

src/QAT/qat/purr/backends/echo.py
src/QAT/qat/purr/backends/qiskit_simulator.py
src/tests/test_qiskit_backend.py

The PR here https://github.com/oqc-community/qat/pull/77 fails for some reason. Trying this new one that's not coming from a private fork

Ported qiskit simulator strict placement checks

---

src/QAT/qat/purr/compiler/builders.py
src/QAT/qat/purr/compiler/devices.py
src/QAT/qat/purr/compiler/instructions.py
src/tests/files/qasm/qasm2/serialize_orphan.qasm
src/tests/test_instructions.py
src/tests/test_qasm.py

Porting changes from develop for this fix.

Fixing issues with lost references when serialising builders.

---

partials/minimal/pyproject.toml
pyproject.toml

Setting version number to 1.1.0 for new releases.

Increased version number to 1.1.0.

---

.github/workflows/cla-assistant.yaml
.github/workflows/doc-build.yml
.github/workflows/doc-publish.yml
.github/workflows/package-build.yaml
.github/workflows/package-publish.yml
.github/workflows/version.yaml

- Adds semi-automatic version control. Basically allows one to tag latest main
- Adds a conditional to publish only when a tag with a specific format is pushed to main

CI improvements

---

src/qat/purr/backends/qblox/codegen.py
src/qat/purr/backends/qblox/config.py
src/qat/purr/backends/qblox/constants.py
src/qat/purr/backends/qblox/device.py
tests/qat/qblox/builder_nuggets.py
tests/qat/qblox/test_codegen.py
tests/qat/qblox/test_config.py

- Manipulate digital offset when the pulse envelope is trivial such as a square
- Make code reusable between a drive pulse and a measure pulse (+ acquire)
- Sanitisation pulse width

Qblox improvements

---

.github/CODEOWNERS
.github/workflows/package-build.yaml
.github/workflows/package-publish.yml

- Update the cache action version
- Add `--sync` flag to `poetry install` calls in CI

CI updates

---

pyproject.toml
tests/qat/test_experimental_frontends.py
tests/qat/utils.py

Added a context that asserts that threads raise an exception.

Pytest thread exception warnings

---

src/qat/purr/backends/qblox/config.py
src/qat/purr/backends/qblox/device.py
tests/qat/qblox/utils.py

- Minor refactoring
- More convenient milti-level reset
- Auto mixer cal

Qblox auto mixer calibration

---

src/qat/purr/backends/qblox/config.py
src/qat/purr/backends/qblox/device.py
tests/qat/qblox/test_config.py

- Reset SYNC only on allocated module and at the end of execution
- Cleanups

Qblox - Scrap off soft-reset because of added overhead

---

src/qat/purr/compiler/runtime.py

same as https://github.com/oqc-community/qat/pull/172 but same name as @hamidelmaazouz mentioned

Bugfix if last instruction was measure [getting around pipline]

---

src/qat/purr/backends/qblox/codegen.py
src/qat/purr/backends/qblox/device.py
src/qat/purr/backends/qblox/visualisation.py
tests/qat/test_instructions.py

- Helps a lot in debugging
- Plots just the pulse timeline, no awareness of control flow (equivalent to a single sweep point and a single shot).
- Any desired transforms to the I and Q signals can be added later on in another sweep
- Some cleanups
Note:
- Realtime plotting that is control flow aware can be done via walking the program and accumulating updates to the timeline array, but this is enough for now

Port scope and acquisition visualisation for Qblox

---

.github/CODEOWNERS

While I may occasionally put up PRs around integration with my other projects it's rare I'm involved in QAT directly nowadays.

Changing CODEOWNERS file

---

docs/source/conf.py
pyproject.toml

Bump to 2.1.0 in preparation for release

bump to 2.1.0

---

src/qat/purr/utils/serializer.py
tests/qat/test_instructions.py

Enable the json dumping and loading of individual instructions.

Re-enable json dumping and loading of instructions.

---

src/qat/__init__.py
src/qat/compiler/analysis_passes.py
src/qat/compiler/transform_passes.py
src/qat/compiler/validation_passes.py
src/qat/core.py
src/qat/ir/pass_base.py
tests/qat/test_core.py

WIP draft for the rough structure of `qat.core.QAT` etc.

QAT core with parity tests.

---

.github/workflows/package-build.yaml
docs/source/conf.py
pyproject.toml
src/qat/purr/compiler/instructions.py
src/qat/purr/integrations/qasm.py
tests/qat/qasm_utils.py
tests/qat/test_qasm.py

Patch resolving the issue with Qasm3 gates unexpectedly failing.

Fix failing Qasm3 gates
