oqc-community/qat

- src/QAT/qat/purr/integrations/qir.py
- src/tests/files/qir/base_profile_ops.ll
- src/tests/files/qir/basic_cudaq.ll
- src/tests/test_qir.py
Updated ordering didn't reach maturity fast enough so swap back to old ones as they are more commonly used.
> Update QIR method args

- .github/workflows/cla-assistant.yaml
Adjusted misconfigured variables to the CLA assistant bot and added OQC QAT team members to the allow list so that we do not have to sign the CLA when contributing.
The fix won't take affect until merged, there is however a test PR in the private repo showing it working.
> CLA bot action fixes

- src/QAT/qat/purr/compiler/config.py
- src/QAT/qat/purr/compiler/frontends.py
- src/tests/test_qasm.py
Both QASM and QIRs default assumptions are you want a results distribution. QIR didn't have one so switch that over, QASM had a very old binary coercion.
> Default primary IRs to results distriubution

- src/QAT/qat/purr/compiler/devices.py
- src/tests/test_calibration.py
This is a HIGHLY TEMPORARY fix for the Recursion Error that occurs when trying to pickle a larger hardware model. The reason for this is a less than ideal data structure that results in too many recursions for the default Python settings. This issue does not exist in develop and the fix should not be included when we move to that version.
> Highly temporary fix of pickle recursion error, not to be included in develop

- src/QAT/qat/purr/compiler/config.py
Just a quick explainer for the readout mitigation that can be linked to in the client docs.
Also removed the beta feature config blob because it's not used anywhere
> Add readout mitigation documentation

- src/QAT/qat/purr/backends/live_devices.py
Simple change that stops infinite looping between `Instrument.disconnect()` and `Instrument.driver = None`.
> Fix infinite recursion when disconnecting Instruments.

- src/QAT/qat/purr/backends/echo.py
Porting the connectivity concept and associated `apply_setup_to_hardware` improvements from develop. These upgrades will allow for more extensive testing to be done with multiple hardware setups in upcoming work.
**N.B.** This is still backwards compatible as the all-to-all cross resonance channels and default connectivity settings are set to generate the same hardware as before. This is different from the develop version.
> Ported hardware connectivity concept from develop.

- partials/minimal/README.rst
PyPI is unable to render the description when multiple links have the same "name". Adding an additional `_` at the end of the link command fixes this and unblock publishing to PyPI.
> Fixed qat-compiler-minimal readme formatting to allow releasing to PyPI.

- examples/plot_pulse_buffers.py
A fix for https://github.com/oqc-community/qat/issues/117. The method `PhysicalBufferPlotEngine._execute_on_hardware()` should call `QuantumExecutionEngine.create_duration_timeline()` with the instructions list and not qat_file.
> Fix plot pulse buffer example script

- src/QAT/qat/purr/compiler/execution.py
Custom pulses were not accumulating phase correctly like regular pulses. This seems fine for 1q calibrations, but when experimenting with ECR gates comprised of custom pulses this breaks, resulting in any 2q calibrations involving ECR gates to fail as well as Randomized Benchmarking.
> Custom pulses now handled correctly in execution

- src/QAT/qat/purr/backends/live.py
Allow `LiveHardwareModel` to be initiated with all the input arguments supported by `QuantumHardwareModel`.
> Allow configuration of LiveHardwareModel on initistion.

- .github/workflows/version.yaml
- src/QAT/qat/purr/backends/qblox/codegen.py
- src/QAT/qat/purr/backends/qblox/config.py
- src/QAT/qat/purr/backends/qblox/constants.py
- src/QAT/qat/purr/backends/qblox/device.py
- src/QAT/qat/purr/backends/qblox/ir.py
- src/QAT/qat/purr/backends/qblox/live.py
- src/tests/qblox/builder_nuggets.py
- src/tests/qblox/conftest.py
- src/tests/qblox/test_codegen.py
- src/tests/qblox/test_config.py
- src/tests/qblox/test_device.py
- src/tests/qblox/test_live.py
- src/tests/qblox/utils.py
- Qblox (sequencer) config now comes from two sources: the hardware models and the codegen.
- Integration length on the sequencer is now being "properly" dynamically set when readout width changes (following SNR optimisation pass for example). Solution to this actually enables a lot of flexibility (via the builder)
- Enable setting up a few more fields important for mixer calibration
- Minor test refactoring and cleanup
> QBlox config and test improvements

- src/qat/purr/backends/live.py
Currently, startup and dosconnect calls for LiveDeviceEngine return None. Changed to return overall instrument connectivity.
> Implement return values for startup/shutdown methods of LiveDeviceEngine

- .github/workflows/package-build.yaml
The "Load cached venv" step was unable to append the python version to the name of the python venv cache. This was causing sporadic failures of the pipelines. This change will give the step "Set up Python 3.x" and ID "setup-python" so it can correctly fetch the cache.
> Give ID to setup python step

- pyproject.toml
- tests/qat/qasm_utils.py
- tests/qat/test_config.py
- tests/qat/test_logger.py
- tests/qat/test_qasm.py
- tests/qat/test_qat.py
- tests/qat/test_qir.py
- tests/qat/test_quantum_backend.py
- tests/qat/test_serializer.py
- tests/qat/test_verification.py
Resolved Pytest Collection Warnings by renaming classes in the tests tree that should not have `Test` in the name.
> Rename classes with Test in the name.

- src/qat/purr/compiler/runtime.py
Issue link: https://github.com/oqc-community/qat/issues/164
> Fix get_builder. Method will return a model for a passed in InstructionExecutionEngine

- tests/qat/test_readout_mitigation.py
The test checks the functionality to mitigate the readout error using a linear model by running a noisy simulator. It checks that the returned mitigated results fall within a certain tolerance of the expected result.
The problem is that the results are statistical, and by chance can fall outside of this tolerance (it happened about 1% of the time in my checks...).
The solution here isn't a perfect one. As the test is implemented, it would be nearly impossible to reduce the chance to fail to zero in a meaningful way. I have just added some repeats in the experiment to reduce the variance of the (averaged) deviation with the expected result, which should make it pass more reliably. Maybe in the future we should reconsider the purpose of the test, as a test that relies on randomness is not …
> fix: resolve flaky noise simulation test

- src/qat/purr/compiler/runtime.py
Fixes bug with measure is the last instruction which returns tuple from `FluidBuilderWrapper`. Checks if iter has a builder and calls the builders instructions instead. This bug was found in the test case:
```
builder = (get_builder(model)
.X(drive_channel, np.pi / 2.0)
.measure(qubit))
results, _ = execute_instructions(engine, builder)
```
Which only returned a singular acquire. Instead of processing the drive pulse and measure.
> Bugfix if last instruction was measure

- src/qat/purr/utils/benchmarking.py
- tests/qat/test_benchmarking.py
`randomized_benchmarking` throws error if lengths was given as key argument.
> randomized_benchmarking bug

- .github/workflows/package-publish.yml
This changes our package publishing action to run on a tag push. Previously it was intended to run on a 'tag push on main' but in fact it was triggering on a tag OR main. The new flow will trigger on any tag but check that tag is a commit on main and abort if not (thanks to @matt-oqc for this fix on QAT-RPC).
It also checks that the poetry version (in pyproject.toml) precisely matches the tag.
Tag extraction uses https://stackoverflow.com/a/72959712/8179249
> Only make releases from tags on main where poetry version matches tag

- src/qat/purr/qatconfig.py
- tests/qat/test_qatconfig.py
This PR provides patch that introduces a "system"-wide flag to disable pulse duration checks.
> Add flag for bypassing pulse duration limits.

- src/qat/purr/backends/qblox/constants.py
- Intended for frequency validation in internal libraries
> Qblox NCO frequency limits as constants

- src/qat/purr/backends/qblox/device.py
- tests/qat/qblox/test_config.py
- Allows Q1 assembly debugging before installation
- Decouples Qblox resource allocation from package installation. This makes the install() method easily reusable for other internal purposes.
> Completely decouple package allocation from installation

- src/qat/purr/backends/qblox/codegen.py
- src/qat/purr/backends/qblox/ir.py
- tests/qat/qblox/builder_nuggets.py
- tests/qat/qblox/test_codegen.py
- When the waveform envelope is not trivial, try to find an existing waveform entry with the same data.
- Allows further optimisation on the waveform memory
> [Qblox] Reuse complex-shaped waveforms whenever possible

- .gitignore
- poetry.lock
- src/qat/purr/compiler/builders.py
- src/qat/purr/compiler/config.py
- src/qat/purr/compiler/emitter.py
- src/qat/purr/compiler/instructions.py
- src/qat/purr/utils/serializer.py
- tests/qat/test_instructions.py
Splitting `builder.measure()` into sub-methods and introducing `InstructionBlock` types to simplify the recognition and fusing of adjacent measures.
> Measurement Refactor

- .github/release.yml
Adds categorisation of our release notes based on labels added to pull requests. This pull request comes with an implied team consensus that we include 'has appropriate labels' as a check in our code reviewing.
See https://docs.github.com/en/repositories/releasing-projects-on-github/automatically-generated-release-notes
It will look something like this... https://david.gardiner.net.au/assets/2020/07/github-release-notes.png
> Auto-generated release note categorisation based on github PR labels

- docs/source/conf.py
- pyproject.toml
- src/qat/purr/compiler/instructions.py
- tests/qat/test_quantum_backend.py
Fixing a bug where `PostProcess` instructions were not properly mapped into channels in `engine.create_duration_timeline`. Also added a test to verify the generated timeline has the expected types.
> Fix post-processing missing from map and add test.

- src/qat/purr/integrations/features.py
- tests/qat/test_integration_features.py
This fixes a bug where the OpenPulseFeatures class (which generates a json_dict describing our openpulse support on a given hardware model) was not python 3.11 compatible. This incompatibility was caused by one of it's supporting dataclasses having a default which was another (mutable) dataclass. This is not supported but was not checked until python 3.11.
Fortunately, the class(es) in question are (we believe) immutable in practice and so we have marked them immutable with the frozen=True attribute.
This was only spotted downstream because this file was not covered by tests (it wasn't even imported). I have added a basic test which fails without the fix.
>  Make OpenPulseFeatures python 3.11+ compatible

- src/qat/purr/compiler/builders.py
Extract the code to append a measure block to a private method that accepts `**kwargs`.
> Extract append measure block to private method.

- src/qat/purr/compiler/builders.py
- src/qat/purr/compiler/instructions.py
- tests/qat/test_instructions.py
Adjust acquire time validation to allow `Variable`.
> Allow acquire time to be a Variable.

- src/qat/purr/backends/qiskit_simulator.py
- tests/qat/files/qasm/qasm2/split_measure_assign.qasm
- tests/qat/test_qiskit_backend.py
Allow the use of multiple classical registers in `QiskitSimulator` executions.
> Remap measurements to multiple cregs in QiskitSim.

- .github/workflows/doc-publish.yml
- .github/workflows/package-publish.yml
Temporarily block/reject releasing and publishing docs based on tags if the version tag does not match both the package version and the version referenced in the docs config.
@alillistone-OQC Would like you're input on this solution.
> Temporary stop releases with version mismatch.

- src/qat/purr/backends/qiskit_simulator.py
- src/qat/purr/qatconfig.py
- tests/qat/test_qiskit_backend.py
Changes made:
- Options for the `AerSimulator` backend can now be passed via qatconfig.
- A fall-back sequence can be provided for `AerSimulator` if the given method fails.
- If simulations using `automatic` or `statevector` fail due to a lack of resources, by default `AerSimulator` will fall back on its MPS backend with a controlled bond dimension. See #129.
- Some basic documentation for the Qiskit backend.
> Extending qiskit simulator capabilities

- pyproject.toml
- src/qat/purr/backends/utilities.py
- tests/qat/test_utilities.py
Fix the overflow errors thrown by `np.tanh(x)` warnings in various waveforms. The error is thrown (on windows) when the argument `x` is complex with a sufficiently large real component. However, the waveforms are only evaluated against time (a real number), so treating `x` as complex is unnecessary. 
Changes:
- Call `x.real` but return the results as a complex type for consistency (there is no restriction that the waveform returned cannot be complex).
- Added some tests for affected waveforms.
> Resolve np.tanh warnings from soft square waveforms

- src/qat/backend/analysis_passes.py
- src/qat/backend/codegen_base.py
- src/qat/backend/graph.py
- src/qat/backend/transform_passes.py
- src/qat/backend/validation_passes.py
- src/qat/purr/backends/qblox/constants.py
- src/qat/purr/compiler/instructions.py
- src/qat/utils/algorithm.py
- tests/qat/backend/test_passes.py
- tests/qat/utils/builder_nuggets.py
The [original PR](https://github.com/oqc-community/qat/pull/157) was deemed too complex and we decided to split it in three main parts. The [first part](https://github.com/oqc-community/qat/pull/216) is the pass infrastructure, the second part is control-flow infrastructure, and the [third part](https://github.com/oqc-community/qat/pull/219) leverages previous work for a faster Qblox integration. This PR covers only the second part.
- To introduce Control Flow analysis capabilities, we needed to support scoping for Repeat and Sweep instructions which is necessary to help build the control flow graph. Most importantly, it opens the idea of having multiple loop nests with potentially multiple acquisitions within a single builder. Also makes the builder look more like a "function".
- The …
> [EXPERIMENTAL] Part 2: The new Control Flow infrastructure

- src/qat/compiler/validation_passes.py
- src/qat/purr/backends/live.py
- tests/qat/test_quantum_backend.py
**Context:**  validating that an instruction list does not have mid-circuit measurements is currently very expensive. It checks that there are no mid circuit measurements by iterating through the entire instruction set, and checking if a qubit has an acquire instruction appear before a pulse. To do so, it has to resolve the qubit for each pulse. However, this only needs to practically be done once per pulse channel, so we can cache the result and reuse that.
**Changes:**
- Cached the result of resolving_qb_pulse_channel for each quantum target so that it can be reused.
- Fixed an error in the validation that compared acquire and measure channels (maybe this needs to be more robust to consider *both* acquires and measures)
- Added a test to ensure mid-circuit measurements are caught. …
> Performance improvement: mid-circuit measurement validation

- src/qat/backend/analysis_passes.py
- src/qat/purr/backends/qblox/analysis_passes.py
- src/qat/purr/backends/qblox/codegen.py
- src/qat/purr/backends/qblox/constants.py
- src/qat/purr/backends/qblox/live.py
- tests/qat/backend/qblox/test_passes.py
- tests/qat/backend/test_passes.py
- tests/qat/qblox/test_codegen.py
- tests/qat/qblox/test_device.py
- tests/qat/qblox/test_live.py
- tests/qat/utils/builder_nuggets.py
The [original PR](https://github.com/oqc-community/qat/pull/157) was deemed too complex and we decided to split it in three main parts. The [first part](https://github.com/oqc-community/qat/pull/216) is the pass infrastructure, the [second part](https://github.com/oqc-community/qat/pull/217) is control-flow infrastructure, and the third part leverages previous work for a faster Qblox integration. This PR covers only the third part.
- Introduces a new legalisation pass for Qblox. This pass builds upon the target-agnostic `TILegalisationPass` to finalise iterator bound conversion prior to codegen.
- The PreCodegenPass allows one to properly initialise condegen contexts prior to invoking the emitter. This has the role of early register and label allocation for the loop nests in the builder …
> [EXPERIMENTAL] Part 3: Faster Qblox integration

- src/qat/purr/integrations/qasm.py
- tests/qat/qasm_utils.py
- tests/qat/test_qasm.py
Allow reuse of variable as long as it's the same variable. `old_var == var`
> Fix broken Qasm3 gates.

- .github/workflows/package-publish.yml
Adds support for QAT admins to make hotfix-style patch releases x.y.z from a branch by allowing any tag on a branch patch-release/x.y.z to be released. Currently we only enforce that the branch contains the words patch-release. Branches containing this phrase are restricted to QAT admins by github.
> Add support for patch releases

- src/qat/backend/analysis_passes.py
- src/qat/purr/backends/qblox/analysis_passes.py
- src/qat/purr/backends/qblox/live.py
- tests/qat/backend/test_codegen.py
- tests/qat/backend/test_live.py
- tests/qat/utils/builder_nuggets.py
A static `DeviceUpdate` is one that updates an attribute on a target with a value that's known at compile time.
For example `DeviceUpdate(some_channel, "scale", 1)` simply assigns `1` to the attribute `scale` on target `some_channel`. But how come people use this version instead of simply saying `some_channel.scale = 1` ?
In fact, the legacy code processes `DeviceUpdate`s with a structure called `DeviceInjector` not only to "inject" (i.e. assign at runtime) but to "revert" any previous assignment(s) at "some aftermath" (*). It's the injection + reversion guarantee that appeals to people more than the direct way. Therefore `DeviceUpdate(some_channel, "scale", 1)` is roughly equivalent to sth like:
```
try:
old_scale = some_channel.scale
some_channel.scale = 1
finally:
some_channel.scale = …
```
> [EXPERIMENTAL] Skeptical static `DeviceUpdate` instructions

- src/qat/purr/backends/qblox/codegen.py
- src/qat/purr/backends/qblox/constants.py
- tests/qat/utils/builder_nuggets.py
- Loop nest size should not exceed acquisition memory
- Raise for now but long term goal is support batching. In fact, batching might even disappear once we enable on-board post-processing
> [EXPERIMENTAL] Raise a meaningful error when acquisition memory is exceeded

- src/qat/backend/analysis_passes.py
- src/qat/backend/transform_passes.py
- src/qat/backend/validation_passes.py
- src/qat/compiler/transform_passes.py
- src/qat/compiler/validation_passes.py
- src/qat/core.py
- src/qat/ir/pass_base.py
- src/qat/purr/backends/qblox/analysis_passes.py
- src/qat/purr/backends/qblox/codegen.py
- src/qat/purr/backends/qblox/live.py
- src/qat/purr/compiler/runtime.py
- src/qat/runtime/analysis_passes.py
- tests/qat/backend/qblox/test_passes.py
- tests/qat/backend/test_codegen.py
- tests/qat/backend/test_passes.py
- tests/qat/ir/test_pass_infra.py
- tests/qat/runtime/test_runtime.py
Use `QatIR` type as input to all passes. Allows the same pipeline to operate from QASM/QIR all the way down to the executable instructions.
> Adjust passes to use QatIR.

- .github/workflows/cla-assistant.yaml
The cla assistant action has migrated to a new organisation. This aligns it and prevents any issues with the runners unable to resolve the action.
> Update cla action to reflect org change

- benchmarks/a-b_tests/test_pipeline.py
- benchmarks/conftest.py
- benchmarks/run.py
- benchmarks/utils/helpers.py
- pyproject.toml
Added pytest configuration to facilitate A/B benchmark testing as well as a set of A/B tests for `qat.purr` vs `QAT` operation.
Run `poetry run pytest benchmarks --ab-only --ab-grouping` to generate an A/B test report that is grouped and sorted to provide a clear overview of the A vs B performance of each benchmark.
> [Experimental] A/B pipeline tests.
